// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI93zjFh2mpl_668FXsASOTrL74llfMkQ',
    appId: '1:886997786110:web:a39c4c446981cbd98f34af',
    messagingSenderId: '886997786110',
    projectId: 'mobile-computing-project-ixd',
    authDomain: 'mobile-computing-project-ixd.firebaseapp.com',
    storageBucket: 'mobile-computing-project-ixd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQCwdC3RJMPCr_iQBZAxCTCjdDSoZkScs',
    appId: '1:886997786110:android:a68ead46ba150c7f8f34af',
    messagingSenderId: '886997786110',
    projectId: 'mobile-computing-project-ixd',
    storageBucket: 'mobile-computing-project-ixd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAj3jk5tTw8xm9xxhKczUtm4isINEv1CI',
    appId: '1:886997786110:ios:a818667ac3ee8ff88f34af',
    messagingSenderId: '886997786110',
    projectId: 'mobile-computing-project-ixd',
    storageBucket: 'mobile-computing-project-ixd.appspot.com',
    iosClientId: '886997786110-ioueutvjkocbt4tki7t8c25tpe2182ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.artmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAj3jk5tTw8xm9xxhKczUtm4isINEv1CI',
    appId: '1:886997786110:ios:a818667ac3ee8ff88f34af',
    messagingSenderId: '886997786110',
    projectId: 'mobile-computing-project-ixd',
    storageBucket: 'mobile-computing-project-ixd.appspot.com',
    iosClientId: '886997786110-ioueutvjkocbt4tki7t8c25tpe2182ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.artmap',
  );
}
